  CREATE DATABASE control;

  USE control;

  CREATE TABLE user (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY_KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )